(function(){
"use strict";
const DB="free-api-directory-vault", STORE="vault", VERSION=1, ITERATIONS=250000;
let db, vaultKey=null, salt=null, records=[];
const $=s=>document.querySelector(s);
const esc=s=>String(s??"").replace(/[&<>"]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[m]));
function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB,VERSION);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains(STORE))d.createObjectStore(STORE,{keyPath:"id"});};r.onsuccess=()=>{db=r.result;resolve(db)};r.onerror=()=>reject(r.error)});}
function tx(mode,fn){return new Promise((resolve,reject)=>{const t=db.transaction(STORE,mode),s=t.objectStore(STORE),r=fn(s);t.oncomplete=()=>resolve(r?.result);t.onerror=()=>reject(t.error)});}
function getAll(){return tx("readonly",s=>s.getAll()).then(x=>x||[]);}
function put(x){return tx("readwrite",s=>s.put(x));}
function del(id){return tx("readwrite",s=>s.delete(id));}
function b64(buf){return btoa(String.fromCharCode(...new Uint8Array(buf)));}
function unb64(s){return Uint8Array.from(atob(s),c=>c.charCodeAt(0)).buffer;}
async function derive(password,s){const material=await crypto.subtle.importKey("raw",new TextEncoder().encode(password),"PBKDF2",false,["deriveKey"]);return crypto.subtle.deriveKey({name:"PBKDF2",salt:s,iterations:ITERATIONS,hash:"SHA-256"},material,{name:"AES-GCM",length:256},false,["encrypt","decrypt"]);}
async function encrypt(value){const iv=crypto.getRandomValues(new Uint8Array(12));const data=new TextEncoder().encode(value);const ct=await crypto.subtle.encrypt({name:"AES-GCM",iv},vaultKey,data);return {iv:b64(iv),data:b64(ct)};}
async function decrypt(r){const pt=await crypto.subtle.decrypt({name:"AES-GCM",iv:unb64(r.iv)},vaultKey,unb64(r.data));return new TextDecoder().decode(pt);}
function hasVault(){return localStorage.getItem("apiVaultSalt")!==null;}
async function unlock(password){salt=hasVault()?new Uint8Array(unb64(localStorage.getItem("apiVaultSalt"))):crypto.getRandomValues(new Uint8Array(16));vaultKey=await derive(password,salt);if(!hasVault())localStorage.setItem("apiVaultSalt",b64(salt));records=await getAll();for(const r of records){try{r.plain=JSON.parse(await decrypt(r))}catch(_){r.plain=null}}}
function providers(){return Array.isArray(window.API_CATALOG)?window.API_CATALOG:[];}
function providerOptions(selected){return providers().map(p=>'<option value="'+esc(p.name)+'" '+(p.name===selected?"selected":"")+'>'+esc(p.name)+'</option>').join("")}
function renderLogin(message){document.querySelector("#app").innerHTML='<div class="wrap">'+nav()+'<section class="hero"><h1>🔐 My API Keys</h1><p>Encrypted local storage for your API credentials.</p></section><div class="card vault-card"><h2>'+(hasVault()?"Unlock your vault":"Create your vault")+'</h2><p class="muted">'+(hasVault()?"Enter your vault password. Your password is never sent anywhere.":"Choose a vault password. If you forget it, the encrypted keys cannot be recovered without an export.")+'</p><input id="vault-pass" class="input" type="password" placeholder="Vault password" autocomplete="new-password"><button id="unlock" class="btn">'+(hasVault()?"Unlock":"Create vault")+'</button><div id="vault-msg" class="notice" style="display:none"></div></div></div>';$("#unlock").onclick=async()=>{const p=$("#vault-pass").value;if(p.length<8){showMsg("Use at least 8 characters.");return}try{await unlock(p);renderVault()}catch(e){showMsg("Could not unlock the vault. Check your password.")}}}
function showMsg(m){const x=$("#vault-msg");if(x){x.textContent=m;x.style.display="block"}}
function nav(){return '<nav class="nav"><a class="logo" href="index.html">Free API Directory</a><a href="finder.html">Find an API</a><a href="recommend.html">Build a project</a><a href="compare.html">Compare</a><a href="keys.html">🔐 My API Keys</a><a href="changes.html">Verified / Changed</a><a href="criteria.html">Browse</a></nav>'}
function renderVault(){
document.querySelector("#app").innerHTML='<div class="wrap">'+nav()+'<section class="hero"><h1>🔐 My API Keys</h1><p>Credentials are encrypted with AES-GCM and stored only in this browser. Nothing is uploaded to the directory.</p></section><div class="card tool"><select id="provider" class="select"><option value="">Choose provider…</option>'+providerOptions(new URLSearchParams(location.search).get("provider"))+'</select><input id="label" class="input" placeholder="Credential label (optional)"><input id="key" class="input" type="password" placeholder="Paste API key / token"><button id="save" class="btn">Save key</button><button id="lock" class="btn secondary">Lock vault</button></div><div id="msg"></div><div class="card"><h2>Saved credentials</h2><div id="list"></div></div></div>';
$("#save").onclick=saveKey;$("#lock").onclick=()=>{vaultKey=null;records=[];renderLogin("Locked.")};renderList();
}
async function saveKey(){const p=$("#provider").value,k=$("#key").value.trim(),l=$("#label").value.trim();if(!p||!k){msg("Choose a provider and enter a key.");return}const id=crypto.randomUUID();const enc=await encrypt(JSON.stringify({provider:p,label:l,key:k,created:new Date().toISOString()}));await put({id,...enc,provider:p,label:l});$("#key").value="";msg("Key saved locally and encrypted.");renderList()}
function msg(t){$("#msg").innerHTML='<div class="notice">'+esc(t)+'</div>'}
async function renderList(){records=await getAll();if(!records.length){$("#list").innerHTML='<p class="muted">No keys saved yet. Add one above.</p>';return}$("#list").innerHTML=records.map(r=>'<div class="vault-row"><div><b>'+esc(r.provider)+'</b>'+(r.label?' <span class="muted">· '+esc(r.label)+'</span>':'')+'<br><span class="masked">••••••••••••</span></div><div class="vault-actions"><button class="btn secondary" data-copy="'+esc(r.id)+'">Copy</button><button class="btn secondary" data-del="'+esc(r.id)+'">Delete</button></div></div>').join("");document.querySelectorAll("[data-copy]").forEach(b=>b.onclick=async()=>{const r=records.find(x=>x.id===b.dataset.copy);try{const p=JSON.parse(await decrypt(r));await navigator.clipboard.writeText(p.key);msg("Key copied to your clipboard. It remains local to your device.")}catch(_){msg("Could not decrypt this key.")}});document.querySelectorAll("[data-del]").forEach(b=>b.onclick=async()=>{if(confirm("Delete this saved API key from this browser?")){await del(b.dataset.del);renderList()}})}
(async()=>{try{await openDB();renderLogin()}catch(e){document.querySelector("#app").innerHTML='<div class="wrap"><section class="hero"><h1>Vault unavailable</h1><p>This browser does not support the local encrypted storage required by the key vault.</p></section></div>'}})();
})();